customhost = "employee.cryx6nekpbzo.us-east-2.rds.amazonaws.com"
customuser = "admin"
custompass = "gdYHvQgKoUQwYKtatH1N"
customdb = "employee"
custombucket = "pcty-employee"
customregion = "us-east-2"
